# Generated by Django 5.1.15 on 2026-08-28 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g. 'Groceries', 'Rent', 'Utilities')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon identifier (e.g. 'shopping-cart', 'utensils', 'car')", max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text="Hex color code for UI badges and charts (e.g. '#10B981')", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category_name')],
            },
        ),
    ]
