# Generated by Django 5.1.15 on 2026-08-28 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary amount in standard currency unit (must be > 0.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, help_text='Optional memo or note for this expense', max_length=255)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='The date on which the expense occurred')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI / Instant Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', help_text='Method used for payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category classifying this expense. Deletion protected if expenses exist.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'expense_date'], name='exp_user_date_idx'), models.Index(fields=['expense_date'], name='exp_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_expense_amount')],
            },
        ),
    ]
